/turtlesim:
  ros__parameters:
    background_b: 35
    background_g: 239
    background_r: 255
    qos_overrides:
      /parameter_events:
        publisher:
          depth: 1000
          durability: volatile
          history: keep_last
          reliability: reliable
    use_sim_time: false

